<div class="my-social">
    <?php if($block->getData('social-1')): ?>
        <div class="social-item">
            <div><img src="<?php echo $block->getData('social-1'); ?>" alt=""></div>
        </div>
    <?php endif; ?>
    <?php if($block->getData('social-2')): ?>
        <div class="social-item">
            <div><img src="<?php echo $block->getData('social-2'); ?>" alt=""></div>
        </div>
    <?php endif; ?>
    <?php if($block->getData('social-3')): ?>
        <div class="social-item">
            <div><img src="<?php echo $block->getData('social-3'); ?>" alt=""></div>
        </div>
    <?php endif; ?>
</div>
